# Generated by Django 6.0 on 2025-12-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('rendszam', models.CharField(max_length=20, unique=True)),
                ('tank_kapacitas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teljesitmeny', models.IntegerField(blank=True, null=True)),
                ('gyartasi_ev', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoFelhasznalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogosultsag', models.CharField(choices=[('tulaj', 'tulaj'), ('hasznalo', 'hasznalo')], max_length=10)),
            ],
            options={
                'db_table': 'auto_felhasznalo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Benzinkut',
            fields=[
                ('benzinkut_id', models.AutoField(primary_key=True, serialize=False)),
                ('nev', models.CharField(blank=True, max_length=255, null=True)),
                ('varos', models.CharField(blank=True, max_length=100, null=True)),
                ('iranyitoszam', models.CharField(blank=True, max_length=10, null=True)),
                ('utca', models.CharField(blank=True, max_length=255, null=True)),
                ('hazszam', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'benzinkut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cim',
            fields=[
                ('cim_id', models.AutoField(primary_key=True, serialize=False)),
                ('orszag', models.CharField(blank=True, max_length=100, null=True)),
                ('varos', models.CharField(max_length=100)),
                ('iranyitoszam', models.CharField(blank=True, max_length=10, null=True)),
                ('utca', models.CharField(blank=True, max_length=255, null=True)),
                ('hazszam', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Karbantartas',
            fields=[
                ('karbantartas_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField()),
                ('leiras', models.TextField(blank=True, null=True)),
                ('koltseg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'karbantartas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('marka_id', models.AutoField(primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'marka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modell',
            fields=[
                ('modell_id', models.AutoField(primary_key=True, serialize=False)),
                ('modellnev', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modell',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Szerviz',
            fields=[
                ('szerviz_id', models.AutoField(primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=255)),
                ('varos', models.CharField(blank=True, max_length=100, null=True)),
                ('iranyitoszam', models.CharField(blank=True, max_length=10, null=True)),
                ('utca', models.CharField(blank=True, max_length=255, null=True)),
                ('hazszam', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'szerviz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tankolas',
            fields=[
                ('tankolas_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField()),
                ('liter', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ar_per_liter', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'tankolas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utvonal',
            fields=[
                ('utvonal_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'utvonal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtvonalHasznalat',
            fields=[
                ('utvonal_hasznalat_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField()),
            ],
            options={
                'db_table': 'utvonal_hasznalat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UzemanyagTipus',
            fields=[
                ('uzemanyag_tipus_id', models.AutoField(primary_key=True, serialize=False)),
                ('megnevezes', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'uzemanyag_tipus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('felhasznalo_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nev', models.CharField(blank=True, max_length=255, null=True)),
                ('szerep', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'felhasznalo',
                'managed': False,
            },
        ),
    ]
