# Generated by Django 6.0 on 2026-02-05 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('tank_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('odometer_km', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.brand')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='AutoApp.brand')),
            ],
            options={
                'db_table': 'car_model',
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('owner', 'owner'), ('driver', 'driver')], max_length=10)),
            ],
            options={
                'db_table': 'car_user',
            },
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('fueling_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=7)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('odometer_km', models.IntegerField()),
            ],
            options={
                'db_table': 'fueling',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'fuel_type',
            },
        ),
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('gas_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'gas_station',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reminder', models.CharField(blank=True, max_length=255, null=True)),
                ('part_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='AutoApp.address')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='AutoApp.address')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='RouteUsage',
            fields=[
                ('route_usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('departure_time', models.IntegerField(blank=True, null=True)),
                ('arrival_time', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'route_usage',
            },
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('service_center_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'service_center',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.DeleteModel(
            name='AutoFelhasznalo',
        ),
        migrations.DeleteModel(
            name='Benzinkut',
        ),
        migrations.DeleteModel(
            name='Cim',
        ),
        migrations.DeleteModel(
            name='Felhasznalo',
        ),
        migrations.DeleteModel(
            name='Karbantartas',
        ),
        migrations.DeleteModel(
            name='Marka',
        ),
        migrations.DeleteModel(
            name='Modell',
        ),
        migrations.DeleteModel(
            name='Szerviz',
        ),
        migrations.DeleteModel(
            name='Tankolas',
        ),
        migrations.DeleteModel(
            name='Utvonal',
        ),
        migrations.DeleteModel(
            name='UtvonalHasznalat',
        ),
        migrations.DeleteModel(
            name='UzemanyagTipus',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.carmodel'),
        ),
        migrations.AddField(
            model_name='caruser',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.car'),
        ),
        migrations.AddField(
            model_name='fueling',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.car'),
        ),
        migrations.AddField(
            model_name='fueling',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.fueltype'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.fueltype'),
        ),
        migrations.AddField(
            model_name='fueling',
            name='gas_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.gasstation'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.car'),
        ),
        migrations.AddField(
            model_name='routeusage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.car'),
        ),
        migrations.AddField(
            model_name='routeusage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.route'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoApp.servicecenter'),
        ),
        migrations.AddField(
            model_name='routeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fueling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='caruser',
            unique_together={('car', 'user')},
        ),
    ]
