# Generated by Django 6.0 on 2026-02-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0002_address_brand_car_carmodel_caruser_fueling_fueltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeusage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
