# Generated by Django 6.0 on 2026-02-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AutoApp", "0004_seed_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="AutoApp.fueltype"),
        ),
        migrations.AlterField(
            model_name="car",
            name="odometer_km",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="average_consumption",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
