# Generated by Django 6.0 on 2026-02-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AutoApp", "0005_car_optional_fields_and_avg_consumption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fueling",
            name="fuel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AutoApp.fueltype",
            ),
        ),
    ]
