# Generated by Django 6.0.2 on 2026-02-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0009_car_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_image',
        ),
        migrations.RemoveField(
            model_name='routeusage',
            name='arrival_delta_min',
        ),
    ]
