# Generated by Codex on 2026-02-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AutoApp", "0010_remove_car_car_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("user", "user"), ("moderator", "moderator")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CommunityCarSetting",
            fields=[
                ("setting_id", models.AutoField(primary_key=True, serialize=False)),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AutoApp.car")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "community_car_setting",
                "unique_together": {("user", "car")},
            },
        ),
        migrations.CreateModel(
            name="CommunityGasStationShare",
            fields=[
                ("share_request_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("approved", "approved"), ("rejected", "rejected")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AutoApp.car")),
                (
                    "gas_station",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AutoApp.gasstation"),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_share_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_gas_station_share",
                "unique_together": {("requester", "car", "gas_station")},
            },
        ),
    ]
