# Generated by Django 4.2.28 on 2026-03-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0009_fueling_route_usage'),
        ('AutoApp', '0015_car_gas_station_metadata'),
    ]

    operations = [
    ]
